
JAVAC=javac
JCFLAGS=-d ../classes -classpath $(CLASSPATH);../classes;../classes/jakarta-regexp-1.2.jar 
Jack=javacc

OUTROOT=../classes
SRCROOT=../src

all: tools-compile compile                                              
                                                                                
tools-compile: \
    $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags \
    $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags 

JCCLIST1=\
    $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.java              \
    $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParserTokenManager.java  \
    $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParserConstants.java     \
    $(SRCROOT)/org/zaval/tools/i18n/translator/ParseException.java   \
    $(SRCROOT)/org/zaval/tools/i18n/translator/Token.java   \
    $(SRCROOT)/org/zaval/tools/i18n/translator/TokenMgrError.java   \
    $(SRCROOT)/org/zaval/tools/i18n/translator/JavaCharStream.java

JCCLIST2=\
    $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.java              \
    $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParserTokenManager.java  \
    $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParserConstants.java     

$(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.java             : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/JavaParserTokenManager.java : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/JavaParserConstants.java    : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/ParserError.java     : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/JavaCharStream.java: $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/Token.java : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/TokenMgrError.java : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags : $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.jj
    cd $(SRCROOT)/org/zaval/tools/i18n/translator
    $(Jack) JavaParser.jj
    cd ../../../../..
    touch $(SRCROOT)/org/zaval/tools/i18n/translator/JavaParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.java             : $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/UtfParserTokenManager.java : $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/UtfParserConstants.java    : $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags

$(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags : $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.jj
    cd $(SRCROOT)/org/zaval/tools/i18n/translator
    $(Jack) UtfParser.jj
    cd ../../../../..
    touch $(SRCROOT)/org/zaval/tools/i18n/translator/UtfParser.flags

compile: